#!/bin/bash
#sudo mount -t cifs -o username=senthil //192.168.85.117/books /home/senthil/Desktop/Windows-Books/
sudo mount -t cifs -o username=senthil //192.168.86.33/books2 /home/senthil/Desktop/Windows-Books/
