#!/bin/bash
#minikuebstatus=$(sudo minikube status 2>&1)
minikuebstatus=$(minikube status 2>&1)
echo $minikuebstatus
if [[ $minikuebstatus == *"host: Running"* ]]; then
  echo "minikube already running. Exiting..."
else
  echo "Starting minikube with driver=kvm2 amd mount"
  #sudo minikube start --driver=none --memory 8192
  #minikube start --driver=docker --memory 8192
  #minikube start --driver=kvm2 --memory 16384 --mount-string="$HOME/git/kubernetes-microservices/:/data" --mount
  #minikube start --driver=kvm2 --memory 8192 --mount-string="$HOME/git/kubernetes-microservices/:/data" --mount
  minikube  start --mount --mount-string="/home/senthil/data:/data2" --driver=kvm2 --memory=16384 --cpus=4
  #minikube  start mount /home/senthil/data:/data2 --driver=kvm2 --memory=16384 --cpus=4
fi

# minikube start --vm-driver=xhyve --container-runtime=docker --show-libmachine-logs --v=10 --alsologtostderr --cpus 4 --memory 8192
# 2023/01/12: minikube  start --mount --mount-string="/home/senthil/opt:/opt" --driver=kvm2 --me│
mory=16384 --cpus=6

