#!/bin/bash
minikuebstatus=$(sudo minikube status 2>&1)
echo $minikuebstatus
if [[ $minikuebstatus == *"host: Running"* ]]; then
  echo "minikube already running. Exiting..."
else
  echo "Starting minikube with driver=none"
  sudo minikube start --driver=none
fi
